"""p0_2_initial_schema

Revision ID: a4b2fdb64036
Revises: 
Create Date: 2026-08-03 21:49:48.139489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4b2fdb64036'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('graph_version', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advisory_runs_started_at', 'advisory_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_advisory_runs_status'), 'advisory_runs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('etf_universe',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('risk_bucket', sa.String(length=32), nullable=False),
    sa.Column('max_allocation_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_leveraged', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_etf_universe_risk_bucket'), 'etf_universe', ['risk_bucket'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'ts', name='uq_fx_rates_pair_ts')
    )
    op.create_index('ix_fx_rates_pair_ts', 'fx_rates', ['pair', 'ts'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('risk_profile', sa.String(length=32), nullable=False),
    sa.Column('available_capital_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocation_conservative_pct', sa.Integer(), nullable=False),
    sa.Column('allocation_moderate_pct', sa.Integer(), nullable=False),
    sa.Column('allocation_aggressive_pct', sa.Integer(), nullable=False),
    sa.Column('investment_horizon', sa.String(length=32), nullable=False),
    sa.Column('favorite_etfs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('financial_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_email_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_series',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'ts', name='uq_macro_series_id_ts')
    )
    op.create_index('ix_macro_series_id_ts', 'macro_series', ['series_id', 'ts'], unique=False)
    op.create_table('market_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity', 'feature_set_version', 'ts', name='uq_market_features_entity_version_ts')
    )
    op.create_index('ix_market_features_entity_ts', 'market_features', ['entity', 'ts'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_kind_created', 'memories', ['kind', 'created_at'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_hash', name='uq_news_articles_raw_hash')
    )
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_channel_created', 'notifications', ['channel', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', name='uq_price_bars_symbol_tf_ts')
    )
    op.create_index('ix_price_bars_symbol_ts', 'price_bars', ['symbol', 'ts'], unique=False)
    op.create_table('agent_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['advisory_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'agent_name', name='uq_agent_results_run_agent')
    )
    op.create_index('ix_agent_results_agent_name', 'agent_results', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_results_run_id'), 'agent_results', ['run_id'], unique=False)
    op.create_table('investor_profile_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'version', name='uq_profile_history_version')
    )
    op.create_index(op.f('ix_investor_profile_history_profile_id'), 'investor_profile_history', ['profile_id'], unique=False)
    op.create_table('news_symbol_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'symbol', name='uq_news_symbol_map')
    )
    op.create_index(op.f('ix_news_symbol_map_article_id'), 'news_symbol_map', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_symbol_map_symbol'), 'news_symbol_map', ['symbol'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('cash_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['investor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_profile_id'), 'portfolios', ['profile_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('size_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('size_amount_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('compliance_status', sa.String(length=32), nullable=False),
    sa.Column('feature_snapshot_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['advisory_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_run_id'), 'recommendations', ['run_id'], unique=False)
    op.create_index('ix_recommendations_status_created', 'recommendations', ['status', 'created_at'], unique=False)
    op.create_index('ix_recommendations_symbol_created', 'recommendations', ['symbol', 'created_at'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'symbol', name='uq_sentiment_article_symbol')
    )
    op.create_index(op.f('ix_sentiment_scores_article_id'), 'sentiment_scores', ['article_id'], unique=False)
    op.create_index('ix_sentiment_scores_symbol_created', 'sentiment_scores', ['symbol', 'created_at'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_holdings_portfolio_symbol')
    )
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('nav_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bucket_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'as_of', name='uq_portfolio_snapshot_as_of')
    )
    op.create_index('ix_portfolio_snapshots_as_of', 'portfolio_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('recommendation_explanations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('realized_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('hit', sa.Boolean(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'horizon_days', name='uq_recommendation_outcome_horizon')
    )
    op.create_index(op.f('ix_recommendation_outcomes_recommendation_id'), 'recommendation_outcomes', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_outcomes_recommendation_id'), table_name='recommendation_outcomes')
    op.drop_table('recommendation_outcomes')
    op.drop_table('recommendation_explanations')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_as_of', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('ix_sentiment_scores_symbol_created', table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_article_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('ix_recommendations_symbol_created', table_name='recommendations')
    op.drop_index('ix_recommendations_status_created', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_run_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_portfolios_profile_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_news_symbol_map_symbol'), table_name='news_symbol_map')
    op.drop_index(op.f('ix_news_symbol_map_article_id'), table_name='news_symbol_map')
    op.drop_table('news_symbol_map')
    op.drop_index(op.f('ix_investor_profile_history_profile_id'), table_name='investor_profile_history')
    op.drop_table('investor_profile_history')
    op.drop_index(op.f('ix_agent_results_run_id'), table_name='agent_results')
    op.drop_index('ix_agent_results_agent_name', table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index('ix_price_bars_symbol_ts', table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index('ix_notifications_channel_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_memories_kind_created', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_market_features_entity_ts', table_name='market_features')
    op.drop_table('market_features')
    op.drop_index('ix_macro_series_id_ts', table_name='macro_series')
    op.drop_table('macro_series')
    op.drop_table('investor_profiles')
    op.drop_index('ix_fx_rates_pair_ts', table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_etf_universe_risk_bucket'), table_name='etf_universe')
    op.drop_table('etf_universe')
    op.drop_index('ix_audit_logs_entity_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_advisory_runs_status'), table_name='advisory_runs')
    op.drop_index('ix_advisory_runs_started_at', table_name='advisory_runs')
    op.drop_table('advisory_runs')
    # ### end Alembic commands ###
